services:
  allhands22:
    image: '${TESTING_IMAGE}'
    ports:
      - 8888:8888

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: '5s'
      start_period: '10s'

  sut:
    image: '${TESTING_IMAGE}'
    depends_on:
      allhands22:
        condition: service_started
      postgres:
        condition: service_healthy
    # run all your tests here against the allhands22 service
    command: curl --fail http://allhands22:8888 || exit 1
