---
# template source: https://github.com/bretfisher/docker-build-workflow/blob/main/templates/call-docker-build.yaml
name: Docker Build

on:
  push:
    branches:
      - main
    # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - '.github/linters/**'
  pull_request:
    # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
  schedule:
    # re-run montly to keep image fresh with upstream base images
    - cron: '0 12 15 * *'
  workflow_dispatch:
    # run manually from Actions tab

jobs:
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to ghcr.io registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: ghcr.io/ductt02/docker-ci-automation:${{ github.run_id }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  unit-test:
    name: Unit Test in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: docker run --rm ghcr.io/ductt02/docker-ci-automation:"$GITHUB_RUN_ID" echo "Unit tests passed"

  integration-test:
    name: Integration Test in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3.6.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests
        run: |
          export TESTING_IMAGE=ghcr.io/ductt02/docker-ci-automation:"$GITHUB_RUN_ID"
          echo Testing image: "$TESTING_IMAGE"
          docker compose -f docker-compose.test.yml up --exit-code-from sut

  CVE-Scan:
    name: CVE Scan
    needs: [build-test-image]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull testing image
        run: docker pull ghcr.io/ductt02/docker-ci-automation:"$GITHUB_RUN_ID"

      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/ductt02/docker-ci-automation:${{ github.run_id }}
          exit-code: 0
          format: 'table'

  build-push-final-image:
    name: Build and Push Final Image
    needs: [unit-test, integration-test, CVE-Scan]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        id: metadata
        uses: docker/metadata-action@v4.6.0
        with:
          images: ductt02/docker-ci-automation,ghcr.io/ductt02/docker-ci-automation
          flavor: |
            latest=false
          tags: |
            type=raw,value=99
            # type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            # type=ref,event=pr
            # type=ref,event=branch
            # type=semver,pattern={{version}}

      - name: Docker Build and Push to GHCR and Docker Hub
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
