---
# template source: https://github.com/bretfisher/docker-build-workflow/blob/main/templates/call-docker-build.yaml
name: Docker Build

on:
  push:
    branches:
      - main
    # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - ".github/linters/**"
  pull_request:
    # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - "README.md"
      - ".github/linters/**"
  schedule:
    # re-run montly to keep image fresh with upstream base images
    - cron: "0 12 15 * *"
  workflow_dispatch:
    # run manually from Actions tab

jobs:
  basic-docker-build:
    name: Docker Build with BuildKit Cache
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v4.1.1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ductt02/docker-ci-automation:latest,ductt02/docker-ci-automation:01
          cache-from: type=gha
          cache-to: type=gha,mode=max
